version: '3.8'

services:
  # Backend service
  backend:
    build: 
      context: ./backend
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    ports:
      - "0.0.0.0:8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/finance_tracker.db
      - SECRET_KEY=${SECRET_KEY:-supersecretkey}
      - ORIGINS=${ORIGINS:-*}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Frontend service
  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:8000/api}
    ports:
      - "0.0.0.0:3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_data:
